[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']
aptPkgs = ['build-essential']

[phases.install]
cmds = [
  'pnpm config set node-linker hoisted',
  'pnpm install --frozen-lockfile'
]
cacheDirectories = ['.pnpm-store']

[phases.build]
cmds = ['pnpm build:prod']
cacheDirectories = ['node_modules/.cache']

[start]
cmd = 'pnpm start'
dependsOn = ['build']

[variables]
NODE_ENV = 'production'
PORT = '3000'
NODE_OPTIONS = '--max-old-space-size=512'
