import { Link } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { 
  Dumbbell, 
  Zap, 
  Target, 
  BarChart3, 
  Calendar, 
  Users,
  ArrowRight,
  CheckCircle,
  Sparkles,
  Timer,
  TrendingUp
} from 'lucide-react'
import { motion } from 'framer-motion'

const HomePage = () => {
  const { isAuthenticated } = useAuth()

  const features = [
    {
      icon: Zap,
      title: 'AI-Powered Workouts',
      description: 'Get personalized CrossFit-Inspired and HIIT workouts generated by advanced AI based on your fitness level, goals, and available equipment.',
      color: 'text-yellow-500'
    },
    {
      icon: Target,
      title: 'Goal-Oriented Training',
      description: 'Set specific fitness goals and receive tailored workout plans that adapt to your progress and preferences.',
      color: 'text-blue-500'
    },
    {
      icon: BarChart3,
      title: 'Progress Tracking',
      description: 'Monitor your performance, track improvements, and visualize your fitness journey with detailed analytics.',
      color: 'text-green-500'
    },
    {
      icon: Calendar,
      title: 'Smart Scheduling',
      description: 'Integrate with your calendar and get workout reminders that fit perfectly into your daily routine.',
      color: 'text-purple-500'
    },
    {
      icon: Timer,
      title: 'Flexible Duration',
      description: 'Choose workout lengths from 15 to 90 minutes that fit your schedule and energy levels.',
      color: 'text-orange-500'
    },
    {
      icon: TrendingUp,
      title: 'Adaptive Difficulty',
      description: 'Workouts automatically adjust based on your feedback and performance to ensure optimal challenge.',
      color: 'text-red-500'
    }
  ]

  const benefits = [
    'Personalized workout plans tailored to your fitness level',
    'AI-powered exercise selection and progression',
    'Equipment-based workout customization',
    'Real-time performance tracking and feedback',
    'Progress analytics and goal achievement insights',
    'Calendar integration for seamless scheduling'
  ]

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative py-20 lg:py-32 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-primary/10 via-background to-secondary/10" />
        <div className="container relative">
          <div className="max-w-4xl mx-auto text-center">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
            >
              <Badge variant="secondary" className="mb-4">
                <Sparkles className="h-3 w-3 mr-1" />
                AI-Powered Fitness
              </Badge>
              <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold tracking-tight mb-6">
                Transform Your
                <span className="text-primary block">Fitness Journey</span>
              </h1>
              <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
                Get personalized CrossFit-Inspired and HIIT workouts powered by AI. 
                Train smarter, track progress, and achieve your fitness goals faster than ever.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                {isAuthenticated ? (
                  <Button size="lg" asChild>
                    <Link to="/dashboard">
                      Go to Dashboard
                      <ArrowRight className="ml-2 h-4 w-4" />
                    </Link>
                  </Button>
                ) : (
                  <>
                    <Button size="lg" asChild>
                      <Link to="/register">
                        Start Free Trial
                        <ArrowRight className="ml-2 h-4 w-4" />
                      </Link>
                    </Button>
                    <Button size="lg" variant="outline" asChild>
                      <Link to="/login">Sign In</Link>
                    </Button>
                  </>
                )}
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-muted/50">
        <div className="container">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Why Choose Muscles?
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Experience the future of fitness with our AI-powered platform designed for serious athletes and fitness enthusiasts.
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
              >
                <Card className="h-full hover:shadow-lg transition-shadow">
                  <CardHeader>
                    <feature.icon className={`h-12 w-12 ${feature.color} mb-4`} />
                    <CardTitle className="text-xl">{feature.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <CardDescription className="text-base">
                      {feature.description}
                    </CardDescription>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-20">
        <div className="container">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl md:text-4xl font-bold mb-6">
                Everything You Need to
                <span className="text-primary block">Reach Your Goals</span>
              </h2>
              <p className="text-lg text-muted-foreground mb-8">
                Our comprehensive platform combines cutting-edge AI technology with proven fitness methodologies to deliver results that matter.
              </p>
              <ul className="space-y-4">
                {benefits.map((benefit, index) => (
                  <motion.li
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.6, delay: index * 0.1 }}
                    className="flex items-start space-x-3"
                  >
                    <CheckCircle className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
                    <span className="text-muted-foreground">{benefit}</span>
                  </motion.li>
                ))}
              </ul>
            </div>
            
            <div className="relative">
              <div className="grid grid-cols-2 gap-4">
                <Card className="p-6">
                  <div className="flex items-center space-x-3 mb-3">
                    <div className="p-2 bg-primary/10 rounded-lg">
                      <Dumbbell className="h-5 w-5 text-primary" />
                    </div>
                    <div>
                      <p className="font-semibold">1000+</p>
                      <p className="text-sm text-muted-foreground">Exercises</p>
                    </div>
                  </div>
                </Card>
                
                <Card className="p-6">
                  <div className="flex items-center space-x-3 mb-3">
                    <div className="p-2 bg-green-500/10 rounded-lg">
                      <Users className="h-5 w-5 text-green-500" />
                    </div>
                    <div>
                      <p className="font-semibold">50K+</p>
                      <p className="text-sm text-muted-foreground">Active Users</p>
                    </div>
                  </div>
                </Card>
                
                <Card className="p-6">
                  <div className="flex items-center space-x-3 mb-3">
                    <div className="p-2 bg-blue-500/10 rounded-lg">
                      <Target className="h-5 w-5 text-blue-500" />
                    </div>
                    <div>
                      <p className="font-semibold">95%</p>
                      <p className="text-sm text-muted-foreground">Goal Achievement</p>
                    </div>
                  </div>
                </Card>
                
                <Card className="p-6">
                  <div className="flex items-center space-x-3 mb-3">
                    <div className="p-2 bg-purple-500/10 rounded-lg">
                      <BarChart3 className="h-5 w-5 text-purple-500" />
                    </div>
                    <div>
                      <p className="font-semibold">4.9/5</p>
                      <p className="text-sm text-muted-foreground">User Rating</p>
                    </div>
                  </div>
                </Card>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-primary text-primary-foreground">
        <div className="container text-center">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Ready to Start Your Transformation?
          </h2>
          <p className="text-xl opacity-90 mb-8 max-w-2xl mx-auto">
            Join thousands of athletes who have already transformed their fitness journey with Muscles.
          </p>
          {!isAuthenticated && (
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button size="lg" variant="secondary" asChild>
                <Link to="/register">
                  Get Started Free
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" className="border-primary-foreground text-primary-foreground hover:bg-primary-foreground hover:text-primary" asChild>
                <Link to="/login">Sign In</Link>
              </Button>
            </div>
          )}
        </div>
      </section>
    </div>
  )
}

export default HomePage

