[phases.setup]
nixPkgs = ['nodejs', 'pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'pnpm preview --host 0.0.0.0 --port $PORT'

[variables]
NODE_ENV = 'production'
PORT = '3000'