CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    email TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    full_name TEXT,
    avatar_url TEXT,
    fitness_level TEXT DEFAULT 'intermediate',
    fitness_goals TEXT[] DEFAULT '{}',
    available_equipment TEXT[] DEFAULT '{}',
    height_cm INTEGER,
    weight_kg DECIMAL(5,2),
    date_of_birth DATE,
    gender TEXT,
    medical_conditions TEXT[] DEFAULT '{}',
    injury_limitations TEXT[] DEFAULT '{}',
    workout_frequency INTEGER,
    preferred_duration INTEGER DEFAULT 45,
    target_body_parts TEXT[] DEFAULT '{}',
    body_type TEXT,
    activity_level TEXT,
    subscription_plan TEXT DEFAULT 'free',
    subscription_status TEXT DEFAULT 'active',
    last_workout_date TIMESTAMP WITH TIME ZONE,
    total_workouts_completed INTEGER DEFAULT 0,
    preferred_workout_time TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);